name: Build Electron Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # 1. UBAH DI SINI: Jangan pakai windows-latest, kunci ke windows-2022 biar stabil
    runs-on: windows-2022
    permissions:
      contents: write

    env:
      GYP_MSVS_VERSION: '2022'
      npm_config_msvs_version: '2022'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2. TAMBAHKAN STEP INI: Mengarahkan compiler C++ langsung ke lokasi Visual Studio 2022
      - name: Set up VCVarsall (C++ Build Tools)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: '14.3' # Ini kode toolset untuk VS 2022

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install Dependencies
        run: npm install

      # 3. UBAH DI SINI: Tambahkan flag msvs_version langsung pas rebuild native modules
      - name: Rebuild Native Modules
        run: npm run rebuild -- --msvs_version=2022
        env:
          npm_config_msvs_version: '2022'

      - name: Build React Frontend
        run: npm run build-react

      - name: Build and Release Electron App
        run: npm run buildwin -- -p always 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Timbangan-EXE
          path: dist/*.exe